[package]
name = "Rust"
version = "0.1.0"
authors = ["Rokas Barasa <50622827+Rokasbarasa1@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
